### ISSUE TITLE
is this library suitable to replicate JSON?

### ISSUE THREAD

**Issue by salzhrani** [peer-base/js-delta-crdts#25]
I have been trying and failing to use delta-crdts to replicate changes made on a JSON object with 4 levels of nesting. using ORMaps has its limitations.
Any thoughts or advice ?

**Comment by pgte** [comment]
Could you be specific on what problems you found?

**Comment by salzhrani** [comment]
It is not the library per say, but the algorithms.
the problems include

- not being able to use non-causal types
- not being able to remove nested ormaps

I worked around the first point by creating a type similar to `mvreg` but returns a single value.
the second point I worked around by storing the keys of an `ormap` in an `rga` and making the array determine which keys exist.

not sure if my workarounds breaks the CRDTs but it is the closest I could get

**Comment by pgte** [comment]
see #27
